# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a42984be9e78b9ddf82d04b996c2b0a6bbf9fa366937144323860a0c5198a19c4a5195b92d18da1d5da99a41d664634864c01687ac6034da4a9dd158726a7311
  facebook_app_id: 163283157350974
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
  secret_key_base: 00b915d201744c62f4275150bf5c63fead710f4b6e3c2460569a873d1444423ada6ad0135a40acce01e070ea755f923cd269f1af622a917813cf5063cdc51e11
  facebook_app_id: 163283157350974
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 163283157350974
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
